In [1]:
import sys
from typing import Dict, Any
import warnings
warnings.filterwarnings('ignore')

def print_header(title: str):
    """Print formatted header"""
    print(f"\n{'='*60}")
    print(f" {title}")
    print(f"{'='*60}")

def print_result(library: str, available: bool, details: str = ""):
    """Print formatted result"""
    status = "✅ Available" if available else "❌ Not Available"
    print(f"{library:<15}: {status}")
    if details:
        print(f"                {details}")

def print_summary(name: str, result: Dict[str, Any]):
    """Print summary for each library"""
    print_header(f"{name} GPU Check")
    if result['version']:
        print(f"📦 Version: {result['version']}")
    else:
        print(f"📦 Not installed")
    
    print_result(name, result['available'], result['details'])
    
    if result['available']:
        print("🎉 Ready for GPU acceleration!")
    else:
        print("⚠️  GPU acceleration not available")

# System Information
print_header("System Information")
print(f"🐍 Python version: {sys.version}")


 System Information
🐍 Python version: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]


In [2]:
print_header("PyTorch GPU Check")

def check_pytorch():
    try:
        import torch
        print(f"📦 PyTorch version: {torch.__version__}")
        
        # CUDA availability
        cuda_available = torch.cuda.is_available()
        print(f"🔍 CUDA available: {cuda_available}")
        
        if cuda_available:
            device_count = torch.cuda.device_count()
            current_device = torch.cuda.current_device()
            device_name = torch.cuda.get_device_name(0)
            
            print(f"🖥️  Device count: {device_count}")
            print(f"🎯 Current device: {current_device}")
            print(f"💾 Device name: {device_name}")
            
            # CUDA version info
            print(f"🔧 CUDA version: {torch.version.cuda}")
            print(f"🏗️  cuDNN version: {torch.backends.cudnn.version()}")
            
            # Simple GPU test
            try:
                print("\n🧪 Running GPU test...")
                x = torch.tensor([1.0, 2.0, 3.0, 4.0]).cuda()
                y = x * 2
                z = torch.matmul(x.unsqueeze(0), y.unsqueeze(1))
                
                print(f"   Input tensor: {x.cpu().numpy()}")
                print(f"   Output tensor: {y.cpu().numpy()}")
                print(f"   Matrix multiplication result: {z.cpu().item()}")
                print("✅ GPU computation successful!")
                
                return True
            except Exception as e:
                print(f"❌ GPU test failed: {str(e)}")
                return False
        else:
            print("❌ CUDA not available")
            return False
            
    except ImportError:
        print("❌ PyTorch not installed")
        return False
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return False

# Run PyTorch check
pytorch_result = check_pytorch()


 PyTorch GPU Check
📦 PyTorch version: 2.7.0+cu126
🔍 CUDA available: True
🖥️  Device count: 1
🎯 Current device: 0
💾 Device name: NVIDIA GeForce RTX 4090
🔧 CUDA version: 12.6
🏗️  cuDNN version: 90501

🧪 Running GPU test...
   Input tensor: [1. 2. 3. 4.]
   Output tensor: [2. 4. 6. 8.]
   Matrix multiplication result: 60.0
✅ GPU computation successful!


In [3]:
print_header("TensorFlow GPU Check")

def check_tensorflow():
    try:
        import os
        os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # Suppress warnings
        
        import tensorflow as tf
        print(f"📦 TensorFlow version: {tf.__version__}")
        
        # GPU device listing
        gpus = tf.config.experimental.list_physical_devices('GPU')
        print(f"🔍 GPUs found: {len(gpus)}")
        
        if len(gpus) > 0:
            for i, gpu in enumerate(gpus):
                print(f"🖥️  GPU {i}: {gpu.name}")
                
            # Memory growth setting (optional)
            try:
                for gpu in gpus:
                    tf.config.experimental.set_memory_growth(gpu, True)
                print("🔧 Memory growth enabled")
            except:
                print("⚠️  Could not enable memory growth")
            
            # Simple GPU test
            try:
                print("\n🧪 Running GPU test...")
                with tf.device('/GPU:0'):
                    a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
                    b = tf.constant([[2.0, 0.0], [0.0, 2.0]])
                    c = tf.matmul(a, b)
                    
                print(f"   Matrix A:\n{a.numpy()}")
                print(f"   Matrix B:\n{b.numpy()}")
                print(f"   A × B:\n{c.numpy()}")
                print("✅ GPU computation successful!")
                
                return True
            except Exception as e:
                print(f"❌ GPU test failed: {str(e)}")
                return False
        else:
            print("❌ No GPU devices found")
            return False
            
    except ImportError:
        print("❌ TensorFlow not installed")
        return False
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return False

# Run TensorFlow check
tensorflow_result = check_tensorflow()


 TensorFlow GPU Check


2025-05-30 03:03:19.401306: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1748541799.410665   12422 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748541799.413501   12422 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748541799.420881   12422 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748541799.420888   12422 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1748541799.420889   12422 computation_placer.cc:177] computation placer alr

📦 TensorFlow version: 2.19.0
🔍 GPUs found: 1
🖥️  GPU 0: /physical_device:GPU:0
🔧 Memory growth enabled

🧪 Running GPU test...
   Matrix A:
[[1. 2.]
 [3. 4.]]
   Matrix B:
[[2. 0.]
 [0. 2.]]
   A × B:
[[2. 4.]
 [6. 8.]]
✅ GPU computation successful!


I0000 00:00:1748541800.772229   12422 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22117 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9


In [4]:
print_header("CatBoost GPU Check")

def check_catboost():
    try:
        import catboost
        from catboost import CatBoostClassifier, CatBoostRegressor
        import numpy as np
        
        print(f"📦 CatBoost version: {catboost.__version__}")
        
        # Test data
        print("🧪 Creating test dataset...")
        X = np.random.randn(100, 5)
        y = np.random.randint(0, 2, 100)
        
        print(f"   Dataset shape: {X.shape}")
        print(f"   Target shape: {y.shape}")
        
        # GPU test
        try:
            print("\n🧪 Testing GPU training...")
            model = CatBoostClassifier(
                iterations=10,
                task_type="GPU",
                devices='0',
                verbose=False,
                random_seed=42
            )
            
            model.fit(X, y, verbose=False)
            predictions = model.predict(X[:5])
            probabilities = model.predict_proba(X[:5])
            
            print(f"   Sample predictions: {predictions}")
            print(f"   Sample probabilities shape: {probabilities.shape}")
            print("✅ GPU training successful!")
            
            return True
            
        except Exception as gpu_error:
            print(f"❌ GPU training failed: {str(gpu_error)}")
            
            # Try CPU fallback
            try:
                print("🔄 Trying CPU training...")
                model_cpu = CatBoostClassifier(
                    iterations=10,
                    verbose=False,
                    random_seed=42
                )
                model_cpu.fit(X, y, verbose=False)
                print("✅ CPU training works")
                print("⚠️  But GPU is not available")
                return False
            except Exception as cpu_error:
                print(f"❌ CPU training also failed: {str(cpu_error)}")
                return False
            
    except ImportError:
        print("❌ CatBoost not installed")
        return False
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return False

# Run CatBoost check
catboost_result = check_catboost()


 CatBoost GPU Check
📦 CatBoost version: 1.2.8
🧪 Creating test dataset...
   Dataset shape: (100, 5)
   Target shape: (100,)

🧪 Testing GPU training...
   Sample predictions: [0 0 0 1 0]
   Sample probabilities shape: (5, 2)
✅ GPU training successful!


In [5]:
print_header("XGBoost GPU Check")

def check_xgboost():
    try:
        import xgboost as xgb
        import numpy as np
        from sklearn.datasets import make_classification
        from sklearn.model_selection import train_test_split
        
        print(f"📦 XGBoost version: {xgb.__version__}")
        
        # Test data
        print("🧪 Creating test dataset...")
        X, y = make_classification(
            n_samples=1000, 
            n_features=10, 
            n_classes=2, 
            random_state=42
        )
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )
        
        print(f"   Training set: {X_train.shape}")
        print(f"   Test set: {X_test.shape}")
        
        # Create DMatrix
        dtrain = xgb.DMatrix(X_train, label=y_train)
        dtest = xgb.DMatrix(X_test, label=y_test)
        
        # GPU test
        try:
            print("\n🧪 Testing GPU training...")
            params_gpu = {
                'tree_method': 'gpu_hist',
                'gpu_id': 0,
                'objective': 'binary:logistic',
                'eval_metric': 'logloss',
                'verbosity': 0,
                'random_state': 42
            }
            
            model_gpu = xgb.train(
                params_gpu,
                dtrain,
                num_boost_round=20,
                evals=[(dtrain, 'train'), (dtest, 'test')],
                verbose_eval=False
            )
            
            # Make predictions
            preds = model_gpu.predict(dtest)
            print(f"   Sample predictions: {preds[:5]}")
            print("✅ GPU training successful!")
            
            return True
            
        except Exception as gpu_error:
            print(f"❌ GPU training failed: {str(gpu_error)}")
            
            # Try CPU fallback
            try:
                print("🔄 Trying CPU training...")
                params_cpu = {
                    'tree_method': 'hist',
                    'objective': 'binary:logistic',
                    'eval_metric': 'logloss',
                    'verbosity': 0,
                    'random_state': 42
                }
                
                model_cpu = xgb.train(
                    params_cpu,
                    dtrain,
                    num_boost_round=20,
                    verbose_eval=False
                )
                print("✅ CPU training works")
                print("⚠️  But GPU is not available")
                return False
            except Exception as cpu_error:
                print(f"❌ CPU training also failed: {str(cpu_error)}")
                return False
                
    except ImportError:
        print("❌ XGBoost not installed")
        return False
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return False

# Run XGBoost check
xgboost_result = check_xgboost()


 XGBoost GPU Check
📦 XGBoost version: 3.0.2
🧪 Creating test dataset...
   Training set: (800, 10)
   Test set: (200, 10)

🧪 Testing GPU training...
   Sample predictions: [0.08655342 0.9932041  0.32216457 0.89159507 0.00507787]
✅ GPU training successful!


In [6]:
print_header("🎯 Final Summary & Recommendations")

# Collect results (run this after all previous cells)
results = {
    'PyTorch': pytorch_result if 'pytorch_result' in locals() else False,
    'TensorFlow': tensorflow_result if 'tensorflow_result' in locals() else False,
    'CatBoost': catboost_result if 'catboost_result' in locals() else False,
    'XGBoost': xgboost_result if 'xgboost_result' in locals() else False
}

# Count GPU-enabled libraries
gpu_enabled = sum(results.values())
total_checked = len(results)

print(f"📊 GPU Status Overview:")
print(f"   Total libraries checked: {total_checked}")
print(f"   GPU-enabled libraries: {gpu_enabled}")
print(f"   GPU success rate: {gpu_enabled/total_checked*100:.1f}%")

print(f"\n📋 Individual Results:")
for lib, status in results.items():
    emoji = "🟢" if status else "🔴"
    print(f"   {emoji} {lib}: {'GPU Ready' if status else 'GPU Not Available'}")

# Recommendations
print(f"\n💡 Recommendations:")
if gpu_enabled == total_checked:
    print("   🎉 Perfect! All libraries can use GPU acceleration.")
    print("   🚀 You're ready for high-performance ML/DL workloads!")
elif gpu_enabled > 0:
    print(f"   ⚠️  {total_checked - gpu_enabled} libraries cannot use GPU.")
    print("   🔧 Check CUDA/driver compatibility for missing libraries.")
else:
    print("   ❌ No GPU acceleration available.")
    print("   🔧 Check your NVIDIA drivers, CUDA installation, and Docker GPU setup.")

print(f"\n🔗 Useful Commands:")
print("   nvidia-smi                    # Check GPU status")
print("   docker run --gpus all ...     # Enable GPU in Docker")
print("   uv add torch --index-url https://download.pytorch.org/whl/cu118  # GPU PyTorch")


 🎯 Final Summary & Recommendations
📊 GPU Status Overview:
   Total libraries checked: 4
   GPU-enabled libraries: 4
   GPU success rate: 100.0%

📋 Individual Results:
   🟢 PyTorch: GPU Ready
   🟢 TensorFlow: GPU Ready
   🟢 CatBoost: GPU Ready
   🟢 XGBoost: GPU Ready

💡 Recommendations:
   🎉 Perfect! All libraries can use GPU acceleration.
   🚀 You're ready for high-performance ML/DL workloads!

🔗 Useful Commands:
   nvidia-smi                    # Check GPU status
   docker run --gpus all ...     # Enable GPU in Docker
   uv add torch --index-url https://download.pytorch.org/whl/cu118  # GPU PyTorch
